export type typeIngredientSupplier = {
  uid?: string; // Unique identifier for the supplier (optional, can be generated by the database)
  data: {
    name?: string; // Name of the supplier
    phone?: number; // Phone number of the supplier
    email?: string; // Email address of the supplier
    address?: string; // Address of the supplier
    city?: string; // City of the supplier
    postalCode?: string; // Postal code of the supplier
    country?: string; // Country of the supplier
    website?: string; // Website of the supplier
    notes?: string; // Additional notes about the supplier
    contactPerson?: string; // Name of the contact person at the supplier
    contactPersonPhone?: number; // Phone number of the contact person
    contactPersonEmail?: string; // Email address of the contact person
    paymentTerms?: string; // Payment terms with the supplier
    deliveryTerms?: string; // Delivery terms with the supplier
    productCategories?: string[]; // Categories of products supplied
    isActive?: boolean; // Flag indicating if the supplier is active
    createdAt?: Date; // Date the supplier was created
    updatedAt?: Date; // Date the supplier was last updated
  };
};
